name: Changelog check

on:
  pull_request:

permissions:
  contents: read

jobs:
  changelog_update:
    runs-on: ubuntu-latest

    name: Is Changelog up-to-date ?
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Check that CHANGELOG.rst was updated
        run: ci/changelog_test.sh
